### ISSUE TITLE
closing parenthesis bug

### ISSUE THREAD

**Issue by rlonka** [majeau-bettez/ecospold2matrix#1]
Hi Guillaume,
there is small bug. There is missing closing parenthesis. I do not have rights to push, 
so I am attaching diff you can  apply. Or just type it yourself. Up to you. It is just one 
')'
In characterisation branch.
[fix_closing_parenthesis.txt](https://github.com/majeau-bettez/ecospold2matrix/files/99010/fix_closing_parenthesis.txt)

**Comment by majeau-bettez** [comment]
Fixed in commit 17bd535. Thanks for finding this.
