### ISSUE TITLE
String error in read_characterisation

### ISSUE THREAD

**Issue by eabouman** [majeau-bettez/ecospold2matrix#3]
Hi Guillaume, 

I received an error executing the following line (2437)
foo.cas = foo.cas.str.replace('^[0]*','')

This only occured for those sheets in ReCiPe111.xlsx where there aren't any cas numbers specified for all stressors (LOP,LTP, WDP,MDP, FDP) . The nans are not recognized by str.replace. 

A quick fix was to implement the following line.

if foo.cas.values.dtype != 'float64':
    foo.cas = foo.cas.str.replace('^[0]*','')

Probably needs a more permanent solution though.

**Comment by majeau-bettez** [comment]
Hi Evert,

Could you post the error message you get? I'd like to handle this with a try-except clause, like:

```
try:
    foo.cas = foo.cas.str.replace('^[0]*','')
except <+error type+>:
    pass
```

**Comment by eabouman** [comment]
foo.cas = foo.cas.str.replace('^[0]*','')
Traceback (most recent call last):

  File "<ipython-input-29-482398a6632a>", line 1, in <module>
    foo.cas = foo.cas.str.replace('^[0]*','')

  File "C:\PROGRAMS\Anaconda\Anaconda3\lib\site-packages\pandas\core\generic.py", line 2355, in __getattr__
    return object.__getattribute__(self, name)

  File "C:\PROGRAMS\Anaconda\Anaconda3\lib\site-packages\pandas\core\base.py", line 212, in __get__
    return self.construct_accessor(instance)

  File "C:\PROGRAMS\Anaconda\Anaconda3\lib\site-packages\pandas\core\strings.py", line 1586, in _make_str_accessor
    raise AttributeError("Can only use .str accessor with string "

AttributeError: Can only use .str accessor with string values, which use np.object_ dtype in pandas

**Comment by majeau-bettez** [comment]
Commit 27acb1f should fix this. For some reason, I could not reproduce the original bug on my machine (because linux?). Could you test that the bug is indeed fixed?
